# Generated by Django 5.0.1 on 2024-01-09 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название группы задач')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Заголовок задачи')),
                ('text', models.TextField(verbose_name='Текст задачи')),
                ('deadline_date', models.DateTimeField(verbose_name='Дата дедлайна')),
                ('finished', models.BooleanField(default=False, verbose_name='Завершена?')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskManager.taskgroup', verbose_name='Группа задач')),
            ],
        ),
    ]
